### PR TITLE
Add a location parameter in resource source

### PR DESCRIPTION
**Pull request by ArthurHlt**
It could be nice to be able to set the location (e.g.: Europe/Paris) for the user like this he could not care about time saving in his country.
For now, we have to set the time zone in start/stop parameter (e.g.: `3 PM +0800`) which are able with this feature just to set the location and omit the time zone, new start and stop values could be simply `3 PM`.

This feature do not change the actual behaviour, the defaults location is set to UTC like it was before.

### CODE REVIEW

**Comment by jfrank-pivotal** [comment]
Merged with minor modifications in commit 0e633b3cf58ba10ea189250f097b26dcf2dc4962

**Comment by ArthurHlt** [comment]
thank you

**Comment by Pirolf** [comment]
Looks like the code is converting the time but not affecting the time. Could you add behavior tests so we can accept the pr? Thanks.

**Comment by ArthurHlt** [comment]
It looks like you accepted it actually.
Well, maybe i get it wrong but the resource seems to need a Time structure and manipulate this, what i intended to do is convert the time from a location to give a Time structure. 
I'm not sure of what you're asking do you need more test with other location than UTC ?

**Comment by vito** [comment]
@ArthurHlt The PR was merged but the story was rejected; I can't get it to work. It needs to use something like `time.ParseInLocation`, which also doesn't work trivially as it'll parse the time as it was in year zero (since our format is just an hour). Time is hard. :( All `time.Now().In(loc)` does is convert the time to the desired location, leaving the absolute time the same.

**Pull request closed without merging**
